# It is recommended not to modify this file,
# as it serves as the initialization file for the node.
#
# Instead, create a copy, place it in the same folder,
# and the iTools Prompt Styler node will read all your style files from there.
#
# Ensure that the formatting is kept the same as in this file.
# Indents in YAML are critical. Ensure proper indentation, as incorrect spacing can cause errors.
#
# Best approach is to copy a block of name, negative_prompt and a prompt and then replace their values
# Note that your text_positive will be added in this part {prompt}
# Adding - name: random will allow the node to pick random name from this file

- name: none
  negative_prompt: ''
  prompt: ''

- name: random
  negative_prompt: ''
  prompt: ''  

- name: squatting
  negative_prompt: ''
  prompt: The subject is in a squatted position, planted feet solid on the ground.
  loras:
    - path: Krea2/action/action_helper.safetensors
      strength: 1.0

- name: dancing
  negative_prompt: ''
  prompt: The subject is dancing, light touch on the ground while turning around and moving her arms and hands in dancing pose.
  loras:
    - path: Krea2/action/face_expression.safetensors
      strength: 1.0

- name: dishes
  negative_prompt: ''
  prompt: The subject is doing the dishes, soapy water overflows the sink.

- name: painting
  negative_prompt: ''
  prompt: The subject is painting an abstract picture, looking concentrated at the model while leaning over towards the ezel holding the painting.
  loras:
    - path: Krea2/action/action_helper.safetensors
      strength: 0.5
    - path: Krea2/action/face_expression.safetensors
      strength: 1.5
